#pragma once

// Name: ANUSGAME, Version: 4.18


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_444EDB2F4C4B64FF24F6DDA4B5777476
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_444EDB2F4C4B64FF24F6DDA4B5777476_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_7C54D86B42A2C9499174D78CADFF59D3
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_7C54D86B42A2C9499174D78CADFF59D3_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2B153A074813E68E8B09CC83CF5FFC84
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2B153A074813E68E8B09CC83CF5FFC84_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_38B8F9A04DEF12274FA2978C4D0EF359
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_38B8F9A04DEF12274FA2978C4D0EF359_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2C06E1084E2F8BA3B5884BAF96EA97D0
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2C06E1084E2F8BA3B5884BAF96EA97D0_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_165C1435453E7DC0397D7392C7185BE8
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_165C1435453E7DC0397D7392C7185BE8_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_ECF433EE4BF132667402AE99DD35DD31
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_ECF433EE4BF132667402AE99DD35DD31_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_AF199C8544728971539B1F9938A26C1B
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_AF199C8544728971539B1F9938A26C1B_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_55FFBBF9493401FCBF350C919E1B4CBD
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_55FFBBF9493401FCBF350C919E1B4CBD_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_BE3959784DC667FA51D23E9DD25702E3
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_BE3959784DC667FA51D23E9DD25702E3_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_77F1A84D4C829389959FA28FE87425C7
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_77F1A84D4C829389959FA28FE87425C7_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_68AADC8B4E25A3293AB4CCBF4F8C3AEE
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_68AADC8B4E25A3293AB4CCBF4F8C3AEE_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_BB78D9884BE856373E021B8A67E09326
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_BB78D9884BE856373E021B8A67E09326_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2FEF49E540AB00AC73BB6E8BEF85D710
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2FEF49E540AB00AC73BB6E8BEF85D710_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_391166654928E1EED22BCFB43D836C4B
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_391166654928E1EED22BCFB43D836C4B_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_C5C43C7248B78C3472BF20B936660237
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_C5C43C7248B78C3472BF20B936660237_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_811675EA4D255659B6D584930A247DA6
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_811675EA4D255659B6D584930A247DA6_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_FD3566A746F643852CCBA3BA509CACF9
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_FD3566A746F643852CCBA3BA509CACF9_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_5BA9B91B4E33DCEE4109E99AC9D00D0D
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_5BA9B91B4E33DCEE4109E99AC9D00D0D_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_FA69590443C64085029980A306326B58
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_FA69590443C64085029980A306326B58_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_E0266567476ACF3B5CE7F3AAF162B7FD
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_E0266567476ACF3B5CE7F3AAF162B7FD_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_F48220E440B03DBB2328DEBB7A74B64B
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_F48220E440B03DBB2328DEBB7A74B64B_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_E31603BB426D195159F0BCB29EA51E6A
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_E31603BB426D195159F0BCB29EA51E6A_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_B28472424585A54C38930F86384BADC4
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_B28472424585A54C38930F86384BADC4_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_B6AA70BE4C6CA7E9B603AA876EC57210
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_B6AA70BE4C6CA7E9B603AA876EC57210_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_8505D5FB4F6415AD74DD1E97F3B2C946
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_8505D5FB4F6415AD74DD1E97F3B2C946_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_D6C36C60402F3D3FD77387A60EE7FB33
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_D6C36C60402F3D3FD77387A60EE7FB33_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_34C673424232F371D9C2FD917E27B648
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_34C673424232F371D9C2FD917E27B648_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_B28EC42A4A0D1B07C436AA965945D360
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_B28EC42A4A0D1B07C436AA965945D360_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_075513D3458E65CC7A1BFD943E9AD288
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_075513D3458E65CC7A1BFD943E9AD288_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_562492E54A33E834C3937BBFFDA30AB9
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_562492E54A33E834C3937BBFFDA30AB9_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_C2D06657423C4978D4D7678144A62652
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_C2D06657423C4978D4D7678144A62652_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_A8EBA29B4D9AAE41778254952BBF7094
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_A8EBA29B4D9AAE41778254952BBF7094_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_89BB3C8A4F751076274DCFB257C0763A
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_89BB3C8A4F751076274DCFB257C0763A_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_714CD04842A246B9E083BAA3D8413DC4
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_714CD04842A246B9E083BAA3D8413DC4_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_86BE5F8E42FF985C7A0B5191E5AB5113
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_86BE5F8E42FF985C7A0B5191E5AB5113_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_C404EF77468D7D5327179CABF5AE3085
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_C404EF77468D7D5327179CABF5AE3085_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_35D71D7E4254391DF8795EB37C256BE2
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_35D71D7E4254391DF8795EB37C256BE2_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_C9B964B84A0751D941C0B8B662A6462F
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_C9B964B84A0751D941C0B8B662A6462F_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_607932524A691CCA405D37BEDE4A25EE
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_607932524A691CCA405D37BEDE4A25EE_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_39A5602A49839606177E8BB161152E77
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_39A5602A49839606177E8BB161152E77_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_286B47044348E9EDCAEDA58099A22C58
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_286B47044348E9EDCAEDA58099A22C58_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_EABD264645B103715F9A368DEBC4A660
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_EABD264645B103715F9A368DEBC4A660_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_32EDC20A430FFFAAAF1EF7AF317E1AEC
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_32EDC20A430FFFAAAF1EF7AF317E1AEC_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_0D5DFC8043E52D09432F27A1D6B5E887
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_0D5DFC8043E52D09432F27A1D6B5E887_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_DC3FAA554D39D990349C94BD083526E2
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_DC3FAA554D39D990349C94BD083526E2_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_87ACAE244CC1F328EAD4529600FCB74E
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_87ACAE244CC1F328EAD4529600FCB74E_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_421355AC41CCA273FF48D4919E3BC6AC
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_421355AC41CCA273FF48D4919E3BC6AC_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2E05D11B44624ADFE4BE06BC24B19D29
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2E05D11B44624ADFE4BE06BC24B19D29_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_4B00D27A46FCA6F6B3709FB3C2BFA4A1
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_4B00D27A46FCA6F6B3709FB3C2BFA4A1_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_65A20ABF4E119F33A7938DB7DADF81C6
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_65A20ABF4E119F33A7938DB7DADF81C6_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_DFE9CFE941227429CF7631863FE3484C
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_DFE9CFE941227429CF7631863FE3484C_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_304950724A537C31E9F6E688B974F042
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_304950724A537C31E9F6E688B974F042_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_169DFD0843EF39B957B81A84F63F162D
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_169DFD0843EF39B957B81A84F63F162D_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_449E612F41CE177BBB703DA955871CD3
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_449E612F41CE177BBB703DA955871CD3_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_C80B0C544DC124C8A3A97F88EC36A1A9
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_C80B0C544DC124C8A3A97F88EC36A1A9_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_A00F37A544764EAC2812D78854A130F5
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_A00F37A544764EAC2812D78854A130F5_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_20FC9A9B41B4432ED1DBAE9422CFC6D2
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_20FC9A9B41B4432ED1DBAE9422CFC6D2_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_026F7C0E447E942FA609F1B934C40BDC
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_026F7C0E447E942FA609F1B934C40BDC_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2DC7F65B4C771374374FA2AF7FD9C8BE
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_2DC7F65B4C771374374FA2AF7FD9C8BE_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_EFABBCA1490ABBE7E4619B95F2415C5A
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_EFABBCA1490ABBE7E4619B95F2415C5A_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_D754B29F421D1D998D02D3A71CF856DD
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_D754B29F421D1D998D02D3A71CF856DD_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_RotationOffsetBlendSpace_B84941AB4AAF203855E9B186785B0ADC
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_RotationOffsetBlendSpace_B84941AB4AAF203855E9B186785B0ADC_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_F8A4DBBA460717E3E60CE2AFCD006716
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_F8A4DBBA460717E3E60CE2AFCD006716_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_RotationOffsetBlendSpace_75E3DE0A42049129BE884D8DDEDEFE6C
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_RotationOffsetBlendSpace_75E3DE0A42049129BE884D8DDEDEFE6C_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_AAD2D6A047F1CB434159F996AD0F645D
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_AAD2D6A047F1CB434159F996AD0F645D_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_122BE8DF45F2C9F0868456BD244CD6C6
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendSpacePlayer_122BE8DF45F2C9F0868456BD244CD6C6_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_C1C889CB4D2786996EC5CCB6C3556530
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_C1C889CB4D2786996EC5CCB6C3556530_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_SequencePlayer_384FF9D94AF52161DC9B3AB70F2FB966
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_SequencePlayer_384FF9D94AF52161DC9B3AB70F2FB966_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_BE3B13D642D3A96BB29EE3A38947889E
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_BlendListByBool_BE3B13D642D3A96BB29EE3A38947889E_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_696ADA7C4DA2353AC5A783A0FFA0890C
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_696ADA7C4DA2353AC5A783A0FFA0890C_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_367B672244841DC79F83FE94F497809E
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_367B672244841DC79F83FE94F497809E_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.BlueprintUpdateAnimation
struct UMixamoBattalionAnimator_C_BlueprintUpdateAnimation_Params
{
	float                                              DeltaTimeX;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.BlueprintInitializeAnimation
struct UMixamoBattalionAnimator_C_BlueprintInitializeAnimation_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.AnimNotify_EnableMovement
struct UMixamoBattalionAnimator_C_AnimNotify_EnableMovement_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.AnimNotify_DisableMovement
struct UMixamoBattalionAnimator_C_AnimNotify_DisableMovement_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.AnimNotify_RFoot
struct UMixamoBattalionAnimator_C_AnimNotify_RFoot_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.AnimNotify_LFoot
struct UMixamoBattalionAnimator_C_AnimNotify_LFoot_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.AnimNotify_HandsEffector
struct UMixamoBattalionAnimator_C_AnimNotify_HandsEffector_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.CheckStepsType
struct UMixamoBattalionAnimator_C_CheckStepsType_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.PlayStep
struct UMixamoBattalionAnimator_C_PlayStep_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_866D9E474CD70BB12C6D19BB4BC672AD
struct UMixamoBattalionAnimator_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimator_AnimGraphNode_TransitionResult_866D9E474CD70BB12C6D19BB4BC672AD_Params
{
};

// Function MixamoBattalionAnimator.MixamoBattalionAnimator_C.ExecuteUbergraph_MixamoBattalionAnimator
struct UMixamoBattalionAnimator_C_ExecuteUbergraph_MixamoBattalionAnimator_Params
{
	int                                                EntryPoint;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
