#pragma once

// Name: ANUSGAME, Version: 4.18


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1D829EE84BBB25D5792DE8B4E8AF7B32
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1D829EE84BBB25D5792DE8B4E8AF7B32_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_234D9B3F464F63E85D87B782339AF3F1
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_234D9B3F464F63E85D87B782339AF3F1_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C48929054551EC3638C336BF308D67D7
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C48929054551EC3638C336BF308D67D7_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_53370C8749A0228AEF7484BC89308812
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_53370C8749A0228AEF7484BC89308812_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C9058D934CA1EF7A0B29EEAD6E6F5979
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C9058D934CA1EF7A0B29EEAD6E6F5979_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_D1EF95B24FE87FE677B2F4B75B977C4E
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_D1EF95B24FE87FE677B2F4B75B977C4E_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_A654CDBA477C4F9B09F130BE6FAC6966
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_A654CDBA477C4F9B09F130BE6FAC6966_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_DF3F795A48A28A2B43F55F91C91E5E6E
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_DF3F795A48A28A2B43F55F91C91E5E6E_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_115172C841271807F922C09B7A7AB56A
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_115172C841271807F922C09B7A7AB56A_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_DA279F824241A79F5739ACB974A222BB
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_DA279F824241A79F5739ACB974A222BB_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_B17E00AA4129323E67D5E78AF808C089
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_B17E00AA4129323E67D5E78AF808C089_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_EC83D8A642BF7548000B9CB3BE43CE1D
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_EC83D8A642BF7548000B9CB3BE43CE1D_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_EF3AF857440358BA1A6CBCA9820A01EB
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_EF3AF857440358BA1A6CBCA9820A01EB_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1B004C29450298E0D3BAFFA0C1E10691
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1B004C29450298E0D3BAFFA0C1E10691_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_11312FD2431586B46DB701A718A59E97
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_11312FD2431586B46DB701A718A59E97_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_B7102E7E4F9CB699B92CD681835A6CD7
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_B7102E7E4F9CB699B92CD681835A6CD7_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_AF3FD3A74D2A7E461E6560A55783F7C3
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_AF3FD3A74D2A7E461E6560A55783F7C3_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1C86288C46282404FA010CB61CC45BD4
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1C86288C46282404FA010CB61CC45BD4_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_25F2D2FD40C631B9D52F1BADDC9254CB
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_25F2D2FD40C631B9D52F1BADDC9254CB_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_D281A8604D943F11D3A3F5A48C6C1590
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_D281A8604D943F11D3A3F5A48C6C1590_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_31756EB44FB160DEE3C08FA3B9B32068
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_31756EB44FB160DEE3C08FA3B9B32068_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_3D3C04D24519FF8FFBCFDFA443584A96
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_3D3C04D24519FF8FFBCFDFA443584A96_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_A73CBD734B67C5A5E2E986A9E7640D5E
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_A73CBD734B67C5A5E2E986A9E7640D5E_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_4673349E4D1AF0BF53A25F85858C5BA4
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_4673349E4D1AF0BF53A25F85858C5BA4_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_DAC9B9D646A861608B782A864015A15A
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_DAC9B9D646A861608B782A864015A15A_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_9FFA1B3F4A6BE1DCB527CC9FEB87EB5A
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_9FFA1B3F4A6BE1DCB527CC9FEB87EB5A_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_426B18514D36989C27AAEB9C2AF1B417
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_426B18514D36989C27AAEB9C2AF1B417_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_E160B69A492720BCE835F29DF1D5FC02
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_E160B69A492720BCE835F29DF1D5FC02_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C2C90A854ADAF93A37200F97598544B7
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C2C90A854ADAF93A37200F97598544B7_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_60DE971042732BE7C94817B45361747B
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_60DE971042732BE7C94817B45361747B_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_069CC0574E80151E1773BA8B5730B032
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_069CC0574E80151E1773BA8B5730B032_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_0DBEB7E541027742DE500A83B1E717AE
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_0DBEB7E541027742DE500A83B1E717AE_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_3ECC65EF4B0C0CB9901FA391D4DE78EA
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_3ECC65EF4B0C0CB9901FA391D4DE78EA_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_FF894E4547BABD21265DD5B629DF1A00
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_FF894E4547BABD21265DD5B629DF1A00_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_CA2B10E44914A7879AD9D28E37957F32
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_CA2B10E44914A7879AD9D28E37957F32_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_9C0EAF964166BF29DB66A5AD81EAB77D
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_9C0EAF964166BF29DB66A5AD81EAB77D_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_B72AE80F417199AE32035AB2049CF579
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_B72AE80F417199AE32035AB2049CF579_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_036E6BCD48AA21DDA54A9A841A65EAE6
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_036E6BCD48AA21DDA54A9A841A65EAE6_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_0A44A0D340C9FC0AD97E199E2BB68621
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_0A44A0D340C9FC0AD97E199E2BB68621_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_4A81D9394048949E4E72D2B15D5B0E52
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_4A81D9394048949E4E72D2B15D5B0E52_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_8759263545F1F7A50D254A917366AF73
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_8759263545F1F7A50D254A917366AF73_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_555F01994F7409FFE7E3B995BA09D290
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_555F01994F7409FFE7E3B995BA09D290_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C6B25B994FFF1092E4AA609FAD9C6328
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_C6B25B994FFF1092E4AA609FAD9C6328_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_99898AF4435DC12524C676925216311C
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_99898AF4435DC12524C676925216311C_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_254113304A79820A169187AE40F45BF4
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_254113304A79820A169187AE40F45BF4_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_804E1BD3470BBA2E9871E58759F9C84B
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_804E1BD3470BBA2E9871E58759F9C84B_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_94FE8EAE425C61045CE0C8AA500AFC5C
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_94FE8EAE425C61045CE0C8AA500AFC5C_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_4F4D21CC4569756A5413499567A7E329
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_4F4D21CC4569756A5413499567A7E329_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_CA51F06F4745FBC7C98802AC2B87CD5E
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_CA51F06F4745FBC7C98802AC2B87CD5E_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1E14DF5B4DD09FD27A72FEB436ED37A7
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_1E14DF5B4DD09FD27A72FEB436ED37A7_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_6CD6F08B4799D597EFA951A91EB6F563
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_6CD6F08B4799D597EFA951A91EB6F563_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_2698A1CF4D21C0701FF9DD974D77540D
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_2698A1CF4D21C0701FF9DD974D77540D_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_45329542431A53F354A098BA7EE19CAB
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_45329542431A53F354A098BA7EE19CAB_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_12CDBDA94A37483D82E92ABB00327A97
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_12CDBDA94A37483D82E92ABB00327A97_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_6661034540123E16436FE2B308F610D6
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_6661034540123E16436FE2B308F610D6_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_0747005242308ECA517443AC1A1F6C1F
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_0747005242308ECA517443AC1A1F6C1F_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_A9C41CEC4DE9BC0FF0FEF38FF3F862AB
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_A9C41CEC4DE9BC0FF0FEF38FF3F862AB_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_75D066594DBE29D784251F94DF35C2A4
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_75D066594DBE29D784251F94DF35C2A4_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_0D34B8534980D0072B0CD2A3D75EE061
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_0D34B8534980D0072B0CD2A3D75EE061_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_F49B8CDC4ED99FE80F32DAA80CFC49B8
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_F49B8CDC4ED99FE80F32DAA80CFC49B8_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_70D74B3A4AB34CA7E943EAA5761AA6EA
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_70D74B3A4AB34CA7E943EAA5761AA6EA_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_FC77F3B24071B6969CC9BA87E0E9845F
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_FC77F3B24071B6969CC9BA87E0E9845F_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_BC120CD3436205D22982CF96BCB549EE
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_BC120CD3436205D22982CF96BCB549EE_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_RotationOffsetBlendSpace_0FC2AFA74B23ED80CFC58A9022966850
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_RotationOffsetBlendSpace_0FC2AFA74B23ED80CFC58A9022966850_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_RotationOffsetBlendSpace_54A8C6AE4AD5EFA820D99EB1B1947D10
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_RotationOffsetBlendSpace_54A8C6AE4AD5EFA820D99EB1B1947D10_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_5E66FAC94E5A306D6882D2B9D44E59E5
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendListByBool_5E66FAC94E5A306D6882D2B9D44E59E5_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.BlueprintUpdateAnimation
struct UMixamoBattalionAnimatorBOT_C_BlueprintUpdateAnimation_Params
{
	float                                              DeltaTimeX;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.AnimNotify_EnableMovement
struct UMixamoBattalionAnimatorBOT_C_AnimNotify_EnableMovement_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.AnimNotify_DisableMovement
struct UMixamoBattalionAnimatorBOT_C_AnimNotify_DisableMovement_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.AnimNotify_RFoot
struct UMixamoBattalionAnimatorBOT_C_AnimNotify_RFoot_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.AnimNotify_LFoot
struct UMixamoBattalionAnimatorBOT_C_AnimNotify_LFoot_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_039C12404F8E1862219348A2C67AB46E
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_BlendSpacePlayer_039C12404F8E1862219348A2C67AB46E_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.CheckLodSystem
struct UMixamoBattalionAnimatorBOT_C_CheckLodSystem_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.CheckStepsType
struct UMixamoBattalionAnimatorBOT_C_CheckStepsType_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.PlayStep
struct UMixamoBattalionAnimatorBOT_C_PlayStep_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_205202DD4962213804FA858248CAEC6D
struct UMixamoBattalionAnimatorBOT_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MixamoBattalionAnimatorBOT_AnimGraphNode_TransitionResult_205202DD4962213804FA858248CAEC6D_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.BlueprintInitializeAnimation
struct UMixamoBattalionAnimatorBOT_C_BlueprintInitializeAnimation_Params
{
};

// Function MixamoBattalionAnimatorBOT.MixamoBattalionAnimatorBOT_C.ExecuteUbergraph_MixamoBattalionAnimatorBOT
struct UMixamoBattalionAnimatorBOT_C_ExecuteUbergraph_MixamoBattalionAnimatorBOT_Params
{
	int                                                EntryPoint;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
